"""hours and events_text

Revision ID: 4b271c53ff28
Revises: 2bdab6eeb841
Create Date: 2025-12-22 18:02:40.046538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b271c53ff28'
down_revision = '2bdab6eeb841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('events_text', sa.String(length=255), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_column('events_text')
        batch_op.drop_column('hours')

    # ### end Alembic commands ###
