"""rm events table

Revision ID: b4bf36f3adf7
Revises: 4b271c53ff28
Create Date: 2026-02-22 09:43:16.812643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bf36f3adf7'
down_revision = '4b271c53ff28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_count', sa.Integer(), nullable=True))
        batch_op.drop_column('events_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_text', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('events_count')

    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=4095), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
